//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from SqueakSpeak.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SqueakSpeakParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISqueakSpeakVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] SqueakSpeakParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.adorableStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdorableStatement([NotNull] SqueakSpeakParser.AdorableStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.extraStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtraStatement([NotNull] SqueakSpeakParser.ExtraStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.nativeCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeCall([NotNull] SqueakSpeakParser.NativeCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.squeakNetGet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqueakNetGet([NotNull] SqueakSpeakParser.SqueakNetGetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.squeakIn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqueakIn([NotNull] SqueakSpeakParser.SqueakInContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.squeakMathCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqueakMathCall([NotNull] SqueakSpeakParser.SqueakMathCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.squeakOut"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSqueakOut([NotNull] SqueakSpeakParser.SqueakOutContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.hugThis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHugThis([NotNull] SqueakSpeakParser.HugThisContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.snugLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSnugLoop([NotNull] SqueakSpeakParser.SnugLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.fluffMagic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFluffMagic([NotNull] SqueakSpeakParser.FluffMagicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.snuggleIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSnuggleIf([NotNull] SqueakSpeakParser.SnuggleIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.snipChoose"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSnipChoose([NotNull] SqueakSpeakParser.SnipChooseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.snipCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSnipCase([NotNull] SqueakSpeakParser.SnipCaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.snipDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSnipDefault([NotNull] SqueakSpeakParser.SnipDefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.bringWarmth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBringWarmth([NotNull] SqueakSpeakParser.BringWarmthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.invokeWhimsy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvokeWhimsy([NotNull] SqueakSpeakParser.InvokeWhimsyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.purrMath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPurrMath([NotNull] SqueakSpeakParser.PurrMathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.leftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLeftExpr([NotNull] SqueakSpeakParser.LeftExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.objectCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectCreation([NotNull] SqueakSpeakParser.ObjectCreationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.fieldAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAssignment([NotNull] SqueakSpeakParser.FieldAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] SqueakSpeakParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.purrOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPurrOperation([NotNull] SqueakSpeakParser.PurrOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.purrOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPurrOperator([NotNull] SqueakSpeakParser.PurrOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.fieldAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldAccess([NotNull] SqueakSpeakParser.FieldAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.purrTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPurrTerm([NotNull] SqueakSpeakParser.PurrTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.nativeCallExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeCallExpr([NotNull] SqueakSpeakParser.NativeCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.baseTerm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseTerm([NotNull] SqueakSpeakParser.BaseTermContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.arrayLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayLiteral([NotNull] SqueakSpeakParser.ArrayLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] SqueakSpeakParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] SqueakSpeakParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SqueakSpeakParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] SqueakSpeakParser.ParamContext context);
}
